name: Publish to WinGet
on:
workflow_dispatch:
  release:
    types: [released]
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Jackett.Jackett
          token: ${{ secrets.WINGET }}
